---

# Variables for the whole Pi cluster

# PXE boot
diskstation_ip: 192.168.1.191
eeprom_working_dir: "/home/pi/tmp_pxe"

# MPI
mpi_working_dir: "/home/pi/tmp_mpi"
mpi_download_url: "https://www.mpich.org/static/downloads/"
mpi_file_version: "3.4a3"
mpi_file_extension: ".tar.gz"

# ATLAS
atlas_working_dir: "/home/pi/tmp_atlas"

# HPL
hpl_working_dir: "/home/pi/tmp_hpl"
hpl_download_url: "http://www.netlib.org/benchmark/hpl/"
hpl_file_version: "hpl-2.3"
hpl_file_extension: ".tar.gz"