---
# tasks file for roles/hpl

- name: Install MPI, ATLAS and required dependencies
  apt:
    pkg:
    - automake
    - gfortran
    - mpich
    - git
    state: latest

- name: Disable CPU throttling - lasts until reboot
  shell: "echo performance | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"

- name: Get ATLAS pre-built - make directory for repo
  file:
    name: "{{ atlas_working_dir }}"
    state: directory
    mode: '0755'
    owner: pi
    group: pi

- name: Add github to known_hosts
  shell: "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  become_user: pi

- name: Get ATLAS pre-built - clone repo to dir
  git:
    repo: https://github.com/mikejmcfarlane/atlas_pi.git
    dest: "{{ atlas_working_dir }}"

- name: Make a working directly for HPL
  file:
    name: "{{ hpl_working_dir }}"
    state: directory
    mode: '0755'
    owner: pi
    group: pi

- name: Get HPL source code
  get_url:
    url: "{{ hpl_download_url }}{{ hpl_file_version }}{{ hpl_file_extension }}"
    dest: "{{ hpl_working_dir }}"

- name: Untar hpl file
  unarchive:
    src: "{{ hpl_working_dir }}/{{ hpl_file_version }}{{ hpl_file_extension }}"
    dest: "{{ hpl_working_dir }}"
    remote_src: yes
  become_user: pi

- name: Setup for make
  command: "sh make_generic"
  args:
    chdir: "{{ hpl_working_dir }}/{{ hpl_file_version }}/setup"
  become_user: pi

- name: Copy in Make.rpi
  template:
    src: templates/Make.rpi.j2
    dest: "{{ hpl_working_dir }}/{{ hpl_file_version }}/Make.rpi"
  become_user: pi

# - name: Make HPL
#   make:
#     chdir: "{{ hpl_working_dir }}/{{ hpl_file_version }}"
#     params:
#       arch: rpi
#   become_user: pi

- name: Add all nodes in cluster to trusted hosts
  shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
  with_inventory_hostnames:
    - current
  become_user: pi

- name: Add HPL.dat
  template:
    src: templates/HPL.dat.j2
    dest: "{{ hpl_working_dir }}/{{ hpl_file_version }}/bin/rpi/HPL.dat"
  become_user: pi

- name: Add nodes-Xpi
  vars:
    node_list: "{{ groups['current'] }}"
  template:
    src: templates/nodes-Xpi.j2
    dest: "{{ hpl_working_dir }}/{{ hpl_file_version }}/bin/rpi/nodes-Xpi"
  become_user: pi

- debug:
    msg: "To test 1 nodes cd {{ hpl_working_dir }}/{{ hpl_file_version }}/bin/rpi/; mpirun -np 4 ./xhpl"

  - debug:
    msg: "To run 4 nodes: cd {{ hpl_working_dir }}/{{ hpl_file_version }}/bin/rpi/; mpiexec -f nodes-Xpi ./xhpl"

- debug:
    msg: "If reboot/shutdown, then need to repeat disable CPU throttle"
