---
# tasks file for roles/common/new_pi_setup

- name: Transfer public ssh key to remote
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
  - key-copy
  - new-pi

- name: Change password
  user:
    name: pi
    password: "{{ new_pi_password }}"
    update_password: always
  tags:
  - new-pi

- name: Update OS
  apt:
    update_cache: yes
    upgrade: 'yes'
  tags:
  - new-pi

# - name: Upgraded OS
#   apt:
#     name: "*"
#     state: latest
#   tags:
#   - new-pi

- name: Install any packages needed in all builds
  apt:
    pkg:
    - vim
    state: latest
  tags:
  - new-pi

# - name: Set hostname, as defined in inventory var
#   hostname:
#     name: "{{ new_hostname }}"

- name: Set hostname, as defined in inventory var
  lineinfile:
    dest: /etc/hostname
    regexp: 'raspberrypi'
    line: "{{ new_hostname }}"
    state: present
  tags:
  - new-pi

- name: Reboot
  reboot:
  tags:
  - new-pi
  

